#!/usr/bin/python3

"""
COMP3311: Acting Script - Assignment 2, T12020
Madeleine Dobbie - z5112961
"""

import sqlite3,sys

if len(sys.argv) != 2 :
  print("Usage:",sys.argv[0],"ACTOR")
  sys.exit(1)

name = sys.argv[1]

con = sqlite3.connect('a2.db')

cur = con.cursor()

cur.execute('SELECT movie.title, director.name, movie.year, movie.content_rating, ROUND(rating.imdb_score,1) FROM actor JOIN acting ON actor.id=acting.actor_id JOIN movie ON acting.movie_id=movie.id LEFT JOIN director ON movie.director_id=director.id JOIN rating ON movie.id=rating.movie_id WHERE actor.name="{}" COLLATE NOCASE ORDER BY movie.year ASC, movie.title ASC'.format(name))

counter = 1
end = []
while True:
  t = cur.fetchone()
  if t == None:
    break
  n,d,y,c,r = t

  if d == None:
    d = ""
  if n == None:
    n = ""
  if c == None:
    c = ""
  if r == None:
    r = ""

  if y == None:
    end.append(t);
  else:
    print('{}. {} -- {} ({}, {}, {})'.format(counter,n,d,y,c,r))
    counter = counter+1;

for i in end:
  n,d,y,c,r = i
  print('{}. {} -- {} ({}, {})'.format(counter,n,d,c,r))

con.close()
