#!/usr/bin/python3

"""
This is a sample program for COMP3311 20T1 Assignment 2 to illustrate how to write an 
executable python code, take in commandline an argument, and connect to a sqlite3 db.
For simplicity (make it short and easier to read), it does not include much error checking,
exception handling and comments.
"""


import sqlite3,sys

if len(sys.argv) != 2 :
  print("Usage:",sys.argv[0],"YEAR")
  sys.exit(1)

year = sys.argv[1]

con = sqlite3.connect('a2.db')

cur = con.cursor()

cur.execute('SELECT id,year FROM movie WHERE year ={} ORDER BY title'.format(year))

while True:
  t = cur.fetchone()
  if t == None:
    break
  x,y = t
  print('{} ({})'.format(x,y))

con.close()
