#!/usr/bin/python3

"""
COMP3311: Title Script - Assignment 2, T12020
Madeleine Dobbie - z5112961
"""

import sqlite3,sys

if len(sys.argv) != 2 :
  print("Usage:",sys.argv[0],"TITLE")
  sys.exit(1)

title = sys.argv[1]

con = sqlite3.connect('a2.db')

cur = con.cursor()

cur.execute('SELECT movie.title,movie.year,movie.content_rating,ROUND(rating.imdb_score,1),GROUP_CONCAT(genre.genre,",") FROM movie JOIN rating ON movie.id=rating.movie_id JOIN genre ON movie.id=genre.movie_id WHERE movie.title LIKE "%{}%" COLLATE NOCASE GROUP BY movie.id ORDER BY movie.year ASC,rating.imdb_score DESC,movie.title ASC'.format(title))

counter = 1
end = []
while True:
  t = cur.fetchone()
  if t == None:
    break
  n,y,c,r,g = t

  if n == None:
    n = ""
  if c == None:
    c = ""
  if r == None:
    r = ""
  if g == None:
    g = ""

  if y == None:
    end.append(t);
  else:
    print('{}. {} ({}, {}, {}) [{}]'.format(counter,n,y,c,r,g))
    counter = counter+1;

for i in end:
  n,y,c,r,g = i
  print('{}. {} ({}, {}) [{}]'.format(counter,n,c,r,g))

con.close()
